version: "3.7"

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digital-fair-portal
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 1234
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: digital-fair-portal
    networks:
      - backend

networks:
  backend:
    driver: bridge