spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**
        - id: fair-service
          uri: lb://fair-service
          predicates:
            - Path=/fairs/**
          filters:
            - AuthenticationFilter

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
